version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build Nx Workspace
          command: yarn nx build kdlcruz.com
      - run:
          name: Run Tests
          command: yarn nx test kdlcruz.com

  deploy:
    working_directory: ~/repo
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build Nx Workspace
          command: yarn nx build kdlcruz.com --prod
      - run:
          name: Deploy to Google Cloud
          command: |
            echo $gcloud_credentials > gcloud-key-file.json
            gcloud auth activate-service-account --key-file=gcloud-key-file.json
            gcloud config set project kdlcruz-183808
            cp ~/repo/apps/kdlcruz.com/app.yaml ~/repo/dist/apps/kdlcruz.com/
            cd ~/repo/dist/apps/kdlcruz.com
            gcloud app deploy app.yaml --quiet --no-promote --set-env-vars GOOGLE_SERVICE_ACCOUNT_EMAIL=$GOOGLE_SERVICE_ACCOUNT_EMAIL GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY GOOGLE_SPREADSHEET_ID=$GOOGLE_SPREADSHEET_ID

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main