version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build Nx Workspace
          command: yarn nx build kdlcruz.com
      - run:
          name: Run Tests
          command: yarn nx test kdlcruz.com
      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*' 

  deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Env Setup
          command: |
            cd ~/repo/apps/kdlcruz.com
            sed -e "s/\$GOOGLE_SERVICE_ACCOUNT_EMAIL/$GOOGLE_SERVICE_ACCOUNT_EMAIL/g" -e "s/\$GOOGLE_PRIVATE_KEY/\"$GOOGLE_PRIVATE_KEY\"/g" -e "s/\$GOOGLE_SPREADSHEET_ID/$GOOGLE_SPREADSHEET_ID/g" app-template.yaml | tee app.yaml
      - run:
          name: Copy app.yaml to dist
          command: |
            cp ~/repo/apps/kdlcruz.com/app.yaml ~/repo/dist/apps/kdlcruz.com/
      - run:
          name: Deploy to Google Cloud
          command: |
            cd ~/repo/dist/apps/kdlcruz.com
            echo $gcloud_credentials > gcloud-key-file.json
            gcloud auth activate-service-account --key-file=gcloud-key-file.json
            gcloud config set project kdlcruz-183808
            gcloud app deploy app.yaml --quiet --no-promote

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main