env: standard
runtime: nodejs20
service: default
handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  GOOGLE_SERVICE_ACCOUNT_EMAIL: 'kdlcruz-com@kdlcruz.iam.gserviceaccount.com'
  GOOGLE_PRIVATE_KEY: -----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCJdKN8gfN9Kmjj
tjlmoxqTRul5QbIyPTNcALfuYzyPawBetjOXfpadIsPhZ0FVIRLD90+JxIQ5JfWT
K+jPiD49KZ5REI7WnmxBu91xcWZlRzYYpFixb6m666OGhSqsdzr9RioW78xBBytY
Rij9GfrNOVZXa36I+i8+cBmWMMCSoBaxqu3dzLex9lwZBnjoiV7axeHzwbC/UkTl
bmlYAEu0MYJ6Fbw13s6YqOY6BlseJMtd5TPHls2Ndw1qb8J4mysZ277ocL6UKK/R
d/ItOESZjsWqsGzEEE5qulrcg8PyxN9kKectoMqETychM8Yz5lhDH8FyfF3JQvG3
siCFOkkNAgMBAAECggEABnPnNzGFi/Ruo0lQarD7pCV8e+Cu5sdd5B2KL5gmhWgP
8XegYTtZguEZLM7Ir8r4mHesGvWoAbkhDRU5sxZnBOmG1luOjQ+NBE1MsRDnrkJN
zTyCh7qMJKt/ttFaZmlxfObV6SjoNTb1h18XI6ycIWq7PX7dHD08dF6rANSN5xl9
t8CrLnjeQs1fo00L3oJnLTebDTSxdsXvTbuVXSJsZ5o9J3JJmzthvuIMt33Z9Gat
v8pCE2wM0NRhD1P8D9XKbgr4xmOi+eXFsr4mPFkldhZift5ffq2lKJMTgp/ddHDp
Pbw7aaqkMnwISq62qPlzAfoKElX3hj1arnvnK1pxEQKBgQC8UwwHltXzCilQ2lf0
4zIfcUbDPkNNIETzvhISYhFxXZE2psx3TcI3zRLQo5TtgQ21/00rMu9kj8LFbgQt
VM3fO8v1F95srFK/I3NYamft7fxp5CjKZYE3cQD4aXTDexKXMtUjXQBrtnWtHO1Z
0GhAaFs6BlVLbeXx83z/icfpMQKBgQC62eeRQqdadZ1XoVauYjGIEkpnxn8d8X42
LFBpdOLm9M8J1Puk++OCaGPk2fRpLPRmhZj7FDB06Cog42CkjjQ+5Mn76xEyijKg
kaDq9aE5LIRkq/LP5r1sUOMWC/V8E7tSoVU5Xsckrc8J42gy2QQ1Av0NP0IQXQ0q
mto7GHMmnQKBgGIgU5BQw8ITdVuvqUzsZN2FRH3PH3o8ajEmxHvXpYcQXe3AE6HG
XoB81mToF115dQ9zq13q+FnJno8IuBx2p569pZRbj4XIdIUrj5puNyD+dBsoyyhK
o32j4AGP0UtaAWHPFseKWgHF3KMLA5FcyjVlKsOdMSxQYxQi7uqnfAbBAoGARHOZ
wvyBJMGbv8OqZr4wWSIiQfxVC1oyG5SGbOvWSDf9NSPigKGKynaFygwS3wkKDBj7
X1gZHGsFLAFAoWg7OaNFX9XQ+gvo2iwfoJQV2UU2x0666HEmiezkFGqTJz5vTKkv
+JGBMS2/gGbgAGjCgs0yeUzoXehI74fFVQry/H0CgYASFsT1e4gQLrMI8cjMaDWR
qQL7GzC0whjIAAT6zPbfsogrX/EHuDEImI9iW05/OL8UucvC5azwZNeA090AJ7Cm
NG/6MYfXcJFcMoCEumMN4EbbIG4pxr5xYiUrl3h/c3KeVi5kUlOwo8WZYrrOr12H
twDPtZWePH97tHgNVhoBZQ==
-----END PRIVATE KEY-----

  GOOGLE_SPREADSHEET_ID: '1RT0zVwJQHKwkTpeyOsF5kPWyokhBGvClrtjXwQzsWOw'